<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="UnityEngine">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AccessibilityModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AIModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AndroidJNIModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AnimationModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ARModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ARModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClothModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClusterInputModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClusterRendererModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ContentLoadModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CrashReportingModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DirectorModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DSPGraphModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GameCenterModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GIModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.GIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GridModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.GridModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.HotReloadModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.InputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.JSONSerializeModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.LocalizationModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.NVIDIAModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ParticleSystemModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PerformanceReportingModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ProfilerModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ProfilerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PropertiesModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ScreenCaptureModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SharedInternalsModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteMaskModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteShapeModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.StreamingModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubstanceModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubsystemsModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainPhysicsModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextCoreFontEngineModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextCoreTextEngineModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TilemapModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TLSModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UmbraModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityConnectModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityCurlModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityTestProtocolModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAudioModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestTextureModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestWWWModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VehiclesModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VFXModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VideoModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VirtualTexturingModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VRModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VRModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.WindModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.WindModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.XRModule">
            <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.XRModule.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NarcoNet.Utilities\NarcoNet.Utilities.csproj"/>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <PropertyGroup>
            <BuildOutputDir>$(MSBuildProjectDirectory)\..\Build\BepInEx\plugins\MadManBeavis-NarcoNet</BuildOutputDir>
        </PropertyGroup>

        <!-- Create output directory structure -->
        <MakeDir Directories="$(BuildOutputDir)"/>

        <!-- Copy the UI DLL -->
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BuildOutputDir)"/>

        <Message Text="NarcoNet.UI copied to: $(BuildOutputDir)" Importance="high"/>
    </Target>

</Project>
