<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="Moq" Version="4.20.72"/>
        <PackageReference Include="xunit" Version="2.9.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NarcoNet\NarcoNet.csproj"/>
        <ProjectReference Include="..\NarcoNet.Utilities\NarcoNet.Utilities.csproj"/>
        <ProjectReference Include="..\NarcoNet.Server\NarcoNet.Server.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\..\BepInEx\core\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="0Harmony20">
        <HintPath>..\..\BepInEx\core\0Harmony20.dll</HintPath>
      </Reference>
      <Reference Include="Accessibility">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Accessibility.dll</HintPath>
      </Reference>
      <Reference Include="AmplifyMotion">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\AmplifyMotion.dll</HintPath>
      </Reference>
      <Reference Include="AnimationSystem.Recording">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\AnimationSystem.Recording.dll</HintPath>
      </Reference>
      <Reference Include="AnimationSystem.Types">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\AnimationSystem.Types.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="Autodesk.Fbx">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Autodesk.Fbx.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>..\..\BepInEx\core\BepInEx.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx.Harmony">
        <HintPath>..\..\BepInEx\core\BepInEx.Harmony.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx.Preloader">
        <HintPath>..\..\BepInEx\core\BepInEx.Preloader.dll</HintPath>
      </Reference>
      <Reference Include="bsg.componentace.compression.libs.zlib">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\bsg.componentace.compression.libs.zlib.dll</HintPath>
      </Reference>
      <Reference Include="bsg.console.core">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\bsg.console.core.dll</HintPath>
      </Reference>
      <Reference Include="bsg.microsoft.extensions.objectpool">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\bsg.microsoft.extensions.objectpool.dll</HintPath>
      </Reference>
      <Reference Include="bsg.system.buffers">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\bsg.system.buffers.dll</HintPath>
      </Reference>
      <Reference Include="BSG.Unity.Wires">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\BSG.Unity.Wires.dll</HintPath>
      </Reference>
      <Reference Include="Cinemachine">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Cinemachine.dll</HintPath>
      </Reference>
      <Reference Include="Coffee.SoftMaskForUGUI">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Coffee.SoftMaskForUGUI.dll</HintPath>
      </Reference>
      <Reference Include="com.nvidia.reflex.Runtime">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\com.nvidia.reflex.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Comfort">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
      </Reference>
      <Reference Include="Comfort.Unity">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Comfort.Unity.dll</HintPath>
      </Reference>
      <Reference Include="CommonExtensions">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\CommonExtensions.dll</HintPath>
      </Reference>
      <Reference Include="DissonanceVoip">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\DissonanceVoip.dll</HintPath>
      </Reference>
      <Reference Include="DOTween">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\DOTween.dll</HintPath>
      </Reference>
      <Reference Include="DOTween.Modules">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\DOTween.Modules.dll</HintPath>
      </Reference>
      <Reference Include="FbxBuildTestAssets">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\FbxBuildTestAssets.dll</HintPath>
      </Reference>
      <Reference Include="FilesChecker">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\FilesChecker.dll</HintPath>
      </Reference>
      <Reference Include="HarmonyXInterop">
        <HintPath>..\..\BepInEx\core\HarmonyXInterop.dll</HintPath>
      </Reference>
      <Reference Include="ItemComponent.Types">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\ItemComponent.Types.dll</HintPath>
      </Reference>
      <Reference Include="ItemTemplate.Types">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\ItemTemplate.Types.dll</HintPath>
      </Reference>
      <Reference Include="JBooth.MicroSplat.Core">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\JBooth.MicroSplat.Core.dll</HintPath>
      </Reference>
      <Reference Include="kcp">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\kcp.dll</HintPath>
      </Reference>
      <Reference Include="LibraryLoaderUtility">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\LibraryLoaderUtility.dll</HintPath>
      </Reference>
      <Reference Include="Meta.XR.Audio">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Meta.XR.Audio.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil">
        <HintPath>..\..\BepInEx\core\Mono.Cecil.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil.Mdb">
        <HintPath>..\..\BepInEx\core\Mono.Cecil.Mdb.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil.Pdb">
        <HintPath>..\..\BepInEx\core\Mono.Cecil.Pdb.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil.Rocks">
        <HintPath>..\..\BepInEx\core\Mono.Cecil.Rocks.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Data.Sqlite">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Mono.Data.Sqlite.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Posix">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Mono.Posix.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Security">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Mono.Security.dll</HintPath>
      </Reference>
      <Reference Include="Mono.WebBrowser">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Mono.WebBrowser.dll</HintPath>
      </Reference>
      <Reference Include="MonoMod.RuntimeDetour">
        <HintPath>..\..\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath>
      </Reference>
      <Reference Include="MonoMod.Utils">
        <HintPath>..\..\BepInEx\core\MonoMod.Utils.dll</HintPath>
      </Reference>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
      </Reference>
      <Reference Include="Newtonsoft.Json.UnityConverters">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.UnityConverters.dll</HintPath>
      </Reference>
      <Reference Include="NLog">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\NLog.dll</HintPath>
      </Reference>
      <Reference Include="Novell.Directory.Ldap">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Novell.Directory.Ldap.dll</HintPath>
      </Reference>
      <Reference Include="Sirenix.OdinInspector.Attributes">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Sirenix.OdinInspector.Attributes.dll</HintPath>
      </Reference>
      <Reference Include="Sirenix.Serialization">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
      </Reference>
      <Reference Include="Sirenix.Serialization.Config">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.Config.dll</HintPath>
      </Reference>
      <Reference Include="Sirenix.Utilities">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Sirenix.Utilities.dll</HintPath>
      </Reference>
      <Reference Include="spt-common">
        <HintPath>..\..\BepInEx\plugins\spt\spt-common.dll</HintPath>
      </Reference>
      <Reference Include="spt-core">
        <HintPath>..\..\BepInEx\plugins\spt\spt-core.dll</HintPath>
      </Reference>
      <Reference Include="spt-custom">
        <HintPath>..\..\BepInEx\plugins\spt\spt-custom.dll</HintPath>
      </Reference>
      <Reference Include="spt-debugging">
        <HintPath>..\..\BepInEx\plugins\spt\spt-debugging.dll</HintPath>
      </Reference>
      <Reference Include="spt-reflection">
        <HintPath>..\..\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
      </Reference>
      <Reference Include="spt-singleplayer">
        <HintPath>..\..\BepInEx\plugins\spt\spt-singleplayer.dll</HintPath>
      </Reference>
      <Reference Include="System.ComponentModel.Composition">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.ComponentModel.Composition.dll</HintPath>
      </Reference>
      <Reference Include="System.Design">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.Design.dll</HintPath>
      </Reference>
      <Reference Include="System.DirectoryServices">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.DirectoryServices.dll</HintPath>
      </Reference>
      <Reference Include="System.Drawing.Design">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.Drawing.Design.dll</HintPath>
      </Reference>
      <Reference Include="System.EnterpriseServices">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.EnterpriseServices.dll</HintPath>
      </Reference>
      <Reference Include="System.IO.Hashing">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.IO.Hashing.dll</HintPath>
      </Reference>
      <Reference Include="System.Runtime.Serialization.Formatters.Soap">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.Runtime.Serialization.Formatters.Soap.dll</HintPath>
      </Reference>
      <Reference Include="System.ServiceModel.Internals">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.ServiceModel.Internals.dll</HintPath>
      </Reference>
      <Reference Include="System.Web.ApplicationServices">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.Web.ApplicationServices.dll</HintPath>
      </Reference>
      <Reference Include="System.Web.Services">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.Web.Services.dll</HintPath>
      </Reference>
      <Reference Include="System.Windows.Forms">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\System.Windows.Forms.dll</HintPath>
      </Reference>
      <Reference Include="uLipSync.Runtime">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\uLipSync.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.AI.Navigation">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.AI.Navigation.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Burst.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst.Unsafe">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Burst.Unsafe.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Collections">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Collections.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Collections.LowLevel.ILSupport">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Formats.Fbx.Runtime">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Formats.Fbx.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Mathematics">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Mathematics.dll</HintPath>
      </Reference>
      <Reference Include="Unity.MemoryProfiler">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.MemoryProfiler.dll</HintPath>
      </Reference>
      <Reference Include="Unity.PlayableGraphVisualizer">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.PlayableGraphVisualizer.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Postprocessing.Runtime">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Postprocessing.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.ProBuilder.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder.Csg">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.ProBuilder.Csg.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder.KdTree">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.ProBuilder.KdTree.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder.Poly2Tri">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.ProBuilder.Poly2Tri.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder.Stl">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.ProBuilder.Stl.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Profiling.Core">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Profiling.Core.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Recorder">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Recorder.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Recorder.Base">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Recorder.Base.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ScriptableBuildPipeline">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.ScriptableBuildPipeline.dll</HintPath>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Timeline">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\Unity.Timeline.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AccessibilityModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AIModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AndroidJNIModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AnimationModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ARModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ARModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AudioModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClothModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterInputModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterRendererModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ContentLoadModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CrashReportingModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DirectorModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DSPGraphModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GameCenterModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GIModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.GIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GridModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.GridModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.HotReloadModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ImageConversionModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.IMGUIModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.InputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.JSONSerializeModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.LocalizationModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.NVIDIAModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ParticleSystemModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PerformanceReportingModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.Physics2DModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PhysicsModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ProfilerModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ProfilerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PropertiesModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ScreenCaptureModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SharedInternalsModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteMaskModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteShapeModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.StreamingModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubstanceModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubsystemsModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainPhysicsModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreFontEngineModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreTextEngineModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TilemapModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TLSModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIElementsModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UmbraModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityConnectModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityCurlModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityTestProtocolModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAudioModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestTextureModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestWWWModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VehiclesModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VFXModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VideoModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VirtualTexturingModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VRModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.VRModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.WindModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.WindModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.XRModule">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\UnityEngine.XRModule.dll</HintPath>
      </Reference>
      <Reference Include="websocket-sharp">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\websocket-sharp.dll</HintPath>
      </Reference>
      <Reference Include="where-allocations">
        <HintPath>..\..\EscapeFromTarkov_Data\Managed\where-allocations.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
